databases:
  - name: hw4_production
    databaseName: hw4_production
    user: hw4_user
    plan: free

services:
  - type: web
    name: hw4
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hw4_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false